image: ubuntu/lts
packages:
  - npm
  - jq
  - curl
  - gtk+3.0
  - chromium-browser
sources:
  - https://git.sr.ht/~gbear605/word-saver
secrets:
  - ecfd2bcd-aa06-44cb-8e3f-068751a71ce6
  - 9ec2af9f-3ed8-4c2f-b02c-53d0daee8fe6
  - 0755116a-2598-41d7-b910-e8d6d97410b3
tasks:
  - setup: |
      sudo npm config set progress=false
      sudo npm install --global web-ext || true
      sudo npm install --global chrome-webstore-upload-cli || true
  - build: |
      cd word-saver
      web-ext lint
      web-ext build
  - setup-test: |
      curl --location "https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US" | tar --extract --verbose --preserve-permissions --bzip2
      cd word-saver/tests
      curl --location "https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz" | tar --extract --verbose --preserve-permissions -z

      CHROME_VERSION=$(curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
      curl --location "http://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip" -o chromedriver.zip
      unzip chromedriver.zip

      npm config set progress=false
      npm install
  - test: |
      cd word-saver/tests
      export FIREFOX_BINARY=/home/build/firefox/firefox
      export CHROME_BINARY=/usr/bin/chromium-browser
      export USE_HEADLESS=true
      node test.js
  - deploy: |
      cd word-saver
      CURRENT_BRANCH=$(git show -s --pretty=%D HEAD | tr -s ', ' '\n' | grep -v HEAD | head -n1)

      MANIFEST_VERSION=$(jq -r .version manifest.json)
      CURRENT_VERSION=$(curl https://greenwichmeanti.me/wordsaver/VERSION.txt)

      if [ $CURRENT_BRANCH = origin/main ] && [ x$MANIFEST_VERSION != x$CURRENT_VERSION ]
      then
        set +x 
        web-ext sign --api-key $(cat ~/jwt_issuer) --api-secret $(cat  ~/jwt_secret)
        EXTENSION_ID=$(cat CHROME_EXTENSION_ID)
        CLIENT_ID=$(cat ~/chrome-webstore-client-id)
        CLIENT_SECRET=$(cat ~/chrome-webstore-client-secret)
        REFRESH_TOKEN=$(cat ~/chrome-webstore-refresh-token)
        webstore upload --auto-publish --source ./web-ext-artifacts/word_saver-$MANIFEST_VERSION.zip
        set -x
        echo $MANIFEST_VERSION > VERSION.txt
        scp -o "StrictHostKeyChecking=no" ./web-ext-artifacts/word_saver-$MANIFEST_VERSION.zip root@greenwichmeanti.me:/var/www/greenwichmeanti.me/public_html/wordsaver
        scp -o "StrictHostKeyChecking=no" ./web-ext-artifacts/word_saver-$MANIFEST_VERSION-an+fx.xpi root@greenwichmeanti.me:/var/www/greenwichmeanti.me/public_html/wordsaver
        scp -o "StrictHostKeyChecking=no" ./VERSION.txt root@greenwichmeanti.me:/var/www/greenwichmeanti.me/public_html/wordsaver
      fi