image: ubuntu/lts
sources:
  - https://git.sr.ht/~gbear605/word-saver
secrets:
  - ecfd2bcd-aa06-44cb-8e3f-068751a71ce6
  - 9ec2af9f-3ed8-4c2f-b02c-53d0daee8fe6
  - 0755116a-2598-41d7-b910-e8d6d97410b3
shell: true
tasks:
  - setup: |
      false
      sudo npm config set progress=false
      sudo npm install --global web-ext || true
  - build: |
      cd word-saver
      web-ext lint
      web-ext build
  - setup-test: |
      curl --location "https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US" | tar --extract --verbose --preserve-permissions --bzip2
      cd word-saver/tests
      curl --location "https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz" | tar --extract --verbose --preserve-permissions -z
      npm install
  - test: |
      cd word-saver/tests
      export FIREFOX_BINARY=/home/build/firefox/firefox
      export USE_HEADLESS=true
      node test.js
  - deploy: |
      cd word-saver
      CURRENT_BRANCH=$(git branch --show-current)
      if [[ $CURRENT_BRANCH = main ]]
      then
        set +x 
        web-ext sign --api-key $(cat ~/jwt_issuer) --api-secret $(cat  ~/jwt_secret)
        set -x
        scp -o "StrictHostKeyChecking=no" ./web-ext-artifacts/word_saver-$(jq -r .version manifest.json).zip root@greenwichmeanti.me:/var/www/greenwichmeanti.me/public_html/wordsaver
        scp -o "StrictHostKeyChecking=no" ./web-ext-artifacts/word_saver-$(jq -r .version manifest.json)-an+fx.xpi root@greenwichmeanti.me:/var/www/greenwichmeanti.me/public_html/wordsaver
      fi